name: Full CI Regression

on: [push, pull_request]

jobs:

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # 3.6 will reach EoL in December 2021
        # https://devguide.python.org/#status-of-python-branches
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
          pip install coveralls
      - name: Run tests
        run: coverage run -m pytest -v
      - name: Submit coveralls
        #if: github.event_name != 'pull_request'
        #run: coveralls
        #env:
        #  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
